Workaround rpm macro issue
This avoids the following error:

  make_install: invalid option -- 'j'
  error: Unknown option j in make_install()
  error: line 224: %make_install PYTHON=python3 %{?_smp_mflags}

The %make_install macro likely needs to be reworked for rpm 4.14,
because this construct worked okay with rpm 4.12.

Signed-off-by: Patrick McCarty <patrick.mccarty@intel.com>